QDRANT_URL = "https://9b818783-ff45-4eab-9a88-36c184ede4fa.us-east4-0.gcp.cloud.qdrant.io:6333"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.DphlnpigEDZMhTkXLpivhyJU-vAew_xFSovkJC-8r3c"
OPENAI_API_KEY = "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"
